package com.sniffydn.sandbox.core.scenario.ui;

import com.sniffydn.sandbox.core.scenario.Action;
import com.sniffydn.sandbox.core.scenario.clothes.Clothes;
import com.sniffydn.sandbox.core.scenario.furniture.FurniturePositions;
import javax.swing.JButton;

public class ClothesRenderer extends javax.swing.JPanel {

    private Clothes clothes;

    /**
     * Creates new form BodyRenderer
     */
    public ClothesRenderer(Clothes clothes) {
        this.clothes = clothes;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        actionsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        actionsPanel.setOpaque(false);
        actionsPanel.setLayout(new java.awt.GridLayout(0, 1));
        add(actionsPanel, java.awt.BorderLayout.EAST);

        jPanel2.setOpaque(false);

        jTextField1.setColumns(20);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${clothes.shortDescription}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.add(jTextField1);
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tool
     */
    public Clothes getClothes() {
        return clothes;
    }

    public void setPosition(FurniturePositions pos) {
        jLabel1.setText(pos.toString());
    }

    public void addAction(Action a) {
        JButton button = new JButton(a.getActionDescription());

        if(a.getActionShortDescription() != null) {
            button.setText(a.getActionShortDescription());
        }

        button.setToolTipText(a.getActionDescription() + "  " + a.getActionType());
        button.addActionListener(a.getActionListener());
        actionsPanel.add(button);
    }

}
