package com.sniffydn.sandbox.core.scenario.ui;

import com.sniffydn.sandbox.core.scenario.Action;
import com.sniffydn.sandbox.core.scenario.ActionType;
import com.sniffydn.sandbox.core.scenario.Tool;
import com.sniffydn.sandbox.core.scenario.clothes.Clothes;
import com.sniffydn.sandbox.core.scenario.furniture.Furniture;
import com.sniffydn.sandbox.core.scenario.furniture.FurniturePositions;
import java.util.List;
import javax.swing.JButton;

public class FurnitureRenderer extends javax.swing.JPanel {

    private Furniture furniture;

    /**
     * Creates new form BodyRenderer
     *
     * @param furniture
     */
    public FurnitureRenderer(Furniture furniture) {
        this.furniture = furniture;
        initComponents();

        for (FurniturePositions pos : furniture.getAvailableToolPositions()) {
            List<Tool> toolList = furniture.getToolMap().get(pos);
            if (toolList != null) {
                for (Tool t : toolList) {
                    if (t instanceof Clothes) {
                        ClothesRenderer clothesRenderer = new ClothesRenderer((Clothes) t);
                        clothesRenderer.setPosition(pos);
                        clothesInPanel.add(clothesRenderer);
                    } else {
                        ToolRenderer toolRenderer = new ToolRenderer(t);
                        toolRenderer.setPosition(pos);
                        toolsInPanel.add(toolRenderer);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        toolsInPanel = new javax.swing.JPanel();
        clothesInPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        actionsPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        toolsInPanel.setBackground(new java.awt.Color(204, 204, 204));
        toolsInPanel.setLayout(new java.awt.GridLayout(0, 1));
        jPanel1.add(toolsInPanel, java.awt.BorderLayout.CENTER);

        clothesInPanel.setBackground(new java.awt.Color(102, 102, 102));
        clothesInPanel.setLayout(new java.awt.GridLayout(0, 1));
        jPanel1.add(clothesInPanel, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jTextField1.setColumns(20);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${furniture.shortDescription}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.add(jTextField1);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        actionsPanel.setLayout(new java.awt.GridLayout(0, 1));
        add(actionsPanel, java.awt.BorderLayout.EAST);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPanel;
    private javax.swing.JPanel clothesInPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel toolsInPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the furniture
     */
    public Furniture getFurniture() {
        return furniture;
    }

    public void addAction(Action a) {
        if (a.getActionType().equals(ActionType.FURNITURE)) {
            JButton button = new JButton(a.getActionDescription());
            button.setToolTipText(a.getActionType().toString());
            button.addActionListener(a.getActionListener());
            actionsPanel.add(button);
        } else {
            System.out.println(this.getClass().getSimpleName() + " deal with " + a);
        }
    }

}
