package com.sniffydn.sandbox.sprite;

import com.sniffydn.sandbox.sprite.model.Action;
import com.sniffydn.sandbox.sprite.model.her.Accessory;
import com.sniffydn.sandbox.sprite.model.her.AccessoryType;
import com.sniffydn.sandbox.sprite.model.her.Her;
import com.sniffydn.sandbox.sprite.model.her.Mood;
import com.sniffydn.sandbox.sprite.model.me.Me;
import com.sniffydn.sandbox.sprite.model.me.Part;
import com.sniffydn.sandbox.sprite.model.me.PartType;
import java.util.List;

/**
 *
 * @author dnyffeler
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        postInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new SpriteLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void postInitComponents() {
//        try {
//            File f = new File(getClass().getResource("/test/Temp/test.p").getPath());
//            System.out.println(f.getAbsoluteFile());
//            Image i = ImageIO.read(f);
//
//            BufferedImage bi = new BufferedImage(216, 216, BufferedImage.TYPE_INT_ARGB);
//            Graphics2D g2d = (Graphics2D) bi.getGraphics();
//
////            g2d.drawImage(i, 0, 0, null);
////            g2d.drawImage(i, 0, -216, null);
////            g2d.drawImage(i, 0, -432, null);
////            g2d.drawImage(i, 0, -648, null);
////            g2d.drawImage(i, 0, -864, null);
//
//            g2d.drawImage(i, -432, 0, null);
//            g2d.drawImage(i, -432, -216, null);
//            g2d.drawImage(i, -432, -432, null);
//            g2d.drawImage(i, -432, -648, null);
//            g2d.drawImage(i, -432, -864, null);
//
////            f = new File("src\\main\\resources\\test1.png");
////            System.out.println(f.getAbsoluteFile());
////            ImageIO.write(bi, "png", f);
//            jLabel1.setIcon(new javax.swing.ImageIcon(bi));
//
//        } catch (IOException ex) {
//            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }

//        Accessory acc = new Accessory();
//        acc.getActions().add(new Action());
//        File f = new File(getClass().getResource("/test/Temp").getPath());
//        File f2 = new File(f.getAbsolutePath() + "/acc/1/desc.xml");
//        System.out.println(f.getAbsolutePath());
//        try {
//            SpriteFS.writeAccessory(f2, acc);
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
        Me me = new Me();

        Part p = me.pickAPart();
        Part p2 = me.pickAPart();
        for (int i = 0; i < 10; i++) {
            System.out.println(p.getName());
            System.out.println("    to " + p2.getName());

            List<Part> path = p.roamToward(p2);
//            System.out.println("\n\n\n\n");
            for(Part prt: path) {
                System.out.println("          -" + prt.getName());
            }

            p = me.pickAPart();
            p2 = me.pickAPart();
        }

        Accessory a = new Accessory();
        a.setType(AccessoryType.LH);
        a.getMoodList().clear();
        a.getMoodList().add(Mood.DOMI);
        a.setName("crop");
        a.setLongDescription("long crop description");
        Action action = new Action();
        action.getMoods().clear();
        action.getMoods().add(Mood.DOMI);
        action.setDescription("lash");
        action.getValidPartTypes().add(PartType.LASHABLE);
        a.getActions().add(action);


        a.getActions().get(0).perform(me, new Her());
    }
}
